MVC_Project/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("bills")]
public partial class Bill
{
    [Key]
    [Column("Bill_id")]
    public int BillId { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; } = null!;

    [Column(TypeName = "decimal(7, 2)")]
    public decimal Costs { get; set; }

    public bool Payed { get; set; }

    [ForeignKey("PhoneNumber")]
    [InverseProperty("Bills")]
    public virtual Phone PhoneNumberNavigation { get; set; } = null!;
}

MVC_Project/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("clients")]
public partial class Client
{
    [Key]
    [Column("Client_id")]
    public int ClientId { get; set; }

    [Column("AFM")]
    [StringLength(50)]
    [Unicode(false)]
    public string Afm { get; set; } = null!;

    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; } = null!;

    [Column("User_id")]
    public int UserId { get; set; }

    [ForeignKey("PhoneNumber")]
    [InverseProperty("Clients")]
    public virtual Phone PhoneNumberNavigation { get; set; } = null!;

    [ForeignKey("UserId")]
    [InverseProperty("Clients")]
    public virtual User User { get; set; } = null!;
}

MVC_Project/Models/Phone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("phones")]
public partial class Phone
{
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; } = null!;

    [Column("Program_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string ProgramName { get; set; } = null!;

    [InverseProperty("PhoneNumberNavigation")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [InverseProperty("PhoneNumberNavigation")]
    public virtual ICollection<Call> Calls { get; set; } = new List<Call>();

    [InverseProperty("PhoneNumberNavigation")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    [ForeignKey("ProgramName")]
    [InverseProperty("Phones")]
    public virtual Program ProgramNameNavigation { get; set; } = null!;
}

MVC_Project/Models/Seller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("sellers")]
public partial class Seller
{
    [Key]
    [Column("Seller_id")]
    public int SellerId { get; set; }

    [Column("User_id")]
    public int UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Sellers")]
    public virtual User User { get; set; } = null!;
}

MVC_Project/ViewModels/CreateClientViewModel.cs
using MVC_Project.Models;

namespace MVC_Project.ViewModels
{
    //Helper Class for CreateClient View
    public class CreateClientViewModel
    {
        public User User { get; set; }
        public Phone Phone { get; set; }
        public Client Client { get; set; }
    }
}

MVC_Project/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using MVC_Project.ViewModels;
using X.PagedList.Extensions;
using MVC_Project.Filters;

namespace MVC_Project.Controllers
{
    [SessionChecker]
    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;
        private readonly LabDBContext _context;

        public ClientController(ILogger<ClientController> logger, LabDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {

            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            return View();
        }

        public async Task<IActionResult> Bills(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(c => c.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(d => d.PhoneNumber).ToList();

            var bills = _context.Bills
                .Include(e => e.PhoneNumberNavigation)
                .Where(e => phoneNumbers.Contains(e.PhoneNumber));

            return View(bills.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.PhoneNumberNavigation)
                .FirstOrDefaultAsync(c => c.BillId == id);

            if (bill == null)
            {
                return NotFound();
            }

            var calls = await _context.Calls
                .Where(d => d.BillId == id)
                .ToListAsync();

            var viewModel = new BillDetailsViewModel
            {
                Bill = bill,
                Calls = calls
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Calls(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(b => b.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(c => c.PhoneNumber).ToList();

            var calls = _context.Calls
                .Include(d => d.PhoneNumberNavigation)
                .Where(d => phoneNumbers.Contains(d.PhoneNumber));

            return View(calls.ToPagedList(page ?? 1, PageSize));
           
        }

        public async Task<IActionResult> Bills_Payment(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(b => b.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(c => c.PhoneNumber).ToList();

            var bills = _context.Bills
                .Include(d => d.PhoneNumberNavigation)
                .Where(d => phoneNumbers.Contains(d.PhoneNumber) && d.Payed == false);

            return View(bills.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> Pay_Form(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.PhoneNumberNavigation)
                .FirstOrDefaultAsync(m => m.BillId == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        [HttpPost]
        public async Task<IActionResult> Pay_Procedure(int card_number, string name, int expiration, int cvv_code, int bill)
        {
            var bill_updated = await _context.Bills.FindAsync(bill);

            if (bill_updated == null)
            {
                return NotFound();
            }

            bill_updated.Payed = true;

            _context.Update(bill_updated);

            await _context.SaveChangesAsync();

            return RedirectToAction("Bills_Payment");
        }

        [SkipSessionChecker]
        public IActionResult Signout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

MVC_Project/Controllers/SellerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using MVC_Project.ViewModels;
using X.PagedList.Extensions;
using MVC_Project.Filters;

namespace MVC_Project.Controllers
{

    [SessionChecker]
    public class SellerController : Controller
    {
        private readonly ILogger<SellerController> _logger;
        private readonly LabDBContext _context;

        public SellerController(ILogger<SellerController> logger, LabDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            return View();
        }

        public IActionResult Clients(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Clients.Include(c => c.PhoneNumberNavigation).Include(c => c.User);

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public IActionResult CreateClient()
        {
            ViewBag.ProgramNames = new SelectList(_context.Programs, "ProgramName", "ProgramName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateClient(CreateClientViewModel createClientViewModel)
        {

            try { 
                _context.Add(createClientViewModel.User);
                await _context.SaveChangesAsync();


                _context.Add(createClientViewModel.Phone);
                await _context.SaveChangesAsync();

                createClientViewModel.Client.UserId = createClientViewModel.User.UserId;
                createClientViewModel.Client.PhoneNumber = createClientViewModel.Phone.PhoneNumber;
           

                _context.Add(createClientViewModel.Client);
                await _context.SaveChangesAsync();

                return RedirectToAction("Clients");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateClient");
            }
        }

        public IActionResult Phones(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Clients.Include(c => c.PhoneNumberNavigation).Include(c => c.User);

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> EditPhone(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Phones.FindAsync(id);

            if (program == null)
            {
                return NotFound();
            }

            ViewBag.ProgramNames = new SelectList(_context.Programs, "ProgramName", "ProgramName");
            return View(program);
        }

        [HttpPost]
        public async Task<IActionResult> EditPhone(Phone phone)
        {
            try
            {
                _context.Update(phone);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhoneExists(phone.PhoneNumber))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction("Phones");
        }

        public IActionResult Bills(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Bills;

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public IActionResult CreateBill()
        {
            ViewData["PhoneNumber"] = new SelectList(_context.Phones, "PhoneNumber", "PhoneNumber");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBill(Bill bill)
        {
            try
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction("Bills");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateBill");
            }
        }

        public IActionResult ClientCalls(string phonenumber, int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var calls = _context.Calls
                .Where(b => b.PhoneNumber == phonenumber) ;

            ViewBag.PhoneNumber = phonenumber;

            return View(calls.ToPagedList(page ?? 1, PageSize));

        }

        [SkipSessionChecker]
        public IActionResult Signout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        private bool PhoneExists(string id)
        {
            return _context.Phones.Any(e => e.PhoneNumber == id);
        }
    }
}

MVC_Project/Views/Seller/Bills.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model X.PagedList.IPagedList<MVC_Project.Models.Bill>

@{
    ViewData["Title"] = "Bills";
}


<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέου πωλητή</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέων προγραμμάτων</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Αλλαγή χαρακτηριστικών προγράμματος</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Clients">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Bills">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Phones">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>
            


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <h2 style="margin-top:12%">Λίστα Λογαριασμών Πελατών</h2>

    <p style="margin-top: 2%">
        <a asp-action="CreateBill" style="background-color:greenyellow; border-radius: 5px; padding: 5px; text-decoration:none; color: black; font-weight:bold">Δημιουργία νέου λογαριασμού</a>
    </p>
    <table class="table" style="background-color: white; border-radius: 8px">
        <thead>
            <tr>
                <th>
                    Κωδικός Λογαριασμού
                </th>
                <th>
                    Ποσό
                </th>
                <th>
                    Πληρωμένος
                </th>
                <th>
                    Τηλεφωνικός Αριθμός
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BillId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Costs) €
                    </td>
                    <td>
                        @(item.Payed ? "Ναι" : "Οχι")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                
                </tr>
            }
        </tbody>
    </table>

    <nav>
        @Html.PagedListPager(Model, page => Url.Action("Bills", new
            {
                page = page
            }), new PagedListRenderOptions()
               {

                   ActiveLiElementClass = "active",
                   PageClasses = new[] { "page-link" },
                   LiElementClasses = new[] { "page-item" },
                   UlElementClasses = new[] { "pagination", "justify-content-center", "mt-3" },
                   LinkToNextPageFormat = "Επόμενη",
                   LinkToPreviousPageFormat = "Προηγούμενη",
                   MaximumPageNumbersToDisplay = 5,
                   DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                   DisplayLinkToNextPage = PagedListDisplayMode.Always,
               })

    </nav>

</body>

MVC_Project/Views/Seller/ClientCalls.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model X.PagedList.IPagedList<MVC_Project.Models.Call>

@{
    ViewData["Title"] = "Client Calls";
}


<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέου πωλητή</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέων προγραμμάτων</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Αλλαγή χαρακτηριστικών προγράμματος</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Clients">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Bills">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Phones">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>
            


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <h2 style="margin-top: 12%"> Προβολή Ιστορικού Κλήσεων Πελάτη</h2>

    <table class="table" style="background-color: white; border-radius: 8px">
        <thead>
            <tr>
                <th>
                    Κωδικός
                </th>
                <th>
                    Τηλεφωνικός Αριθμός
                </th>
                <th>
                    Περιγραφή
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CallId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                </tr>
            }
        </tbody>
    </table>

    <nav>
        @Html.PagedListPager(Model, page => Url.Action("ClientCalls", new
            {
                phonenumber = ViewBag.phonenumber,
                page = page
            }), new PagedListRenderOptions()
   {

       ActiveLiElementClass = "active",
       PageClasses = new[] { "page-link" },
       LiElementClasses = new[] { "page-item" },
       UlElementClasses = new[] { "pagination", "justify-content-center", "mt-3" },
       LinkToNextPageFormat = "Επόμενη",
       LinkToPreviousPageFormat = "Προηγούμενη",
       MaximumPageNumbersToDisplay = 5,
       DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
       DisplayLinkToNextPage = PagedListDisplayMode.Always,
   })

    </nav>

    <div>
        <a asp-action="Phones">Πίσω στους Πελάτες</a>
    </div>

</body>

MVC_Project/Views/Seller/CreateBill.cshtml
@model MVC_Project.Models.Bill

@{
    ViewData["Title"] = "Create Bill";
}


<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέου πωλητή</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Δημιουργία νέων προγραμμάτων</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Αλλαγή χαρακτηριστικών προγράμματος</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Clients">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Bills">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Seller" asp-action="Phones">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>
            


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <h2 style="margin-top: 12%">Δημιουργία Λογαριασμού</h2>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateBill">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Αριθμός Τηλεφώνου</label>
                    <select asp-for="PhoneNumber" class="form-control" asp-items="ViewBag.PhoneNumber"></select>
                </div>
                <div class="form-group" style="margin-top: 5px">
                    <label class="control-label">Κόστος</label>
                    <input asp-for="Costs" type="number" step="0.01" class="form-control" />
                    <span asp-validation-for="Costs" class="text-danger"></span>
                </div>
            
                <input class="form-check-input" asp-for="Payed" value="false" hidden/>
                <div class="form-group" style="margin-top: 5px">
                    <input type="submit" value="Δημιουργία" class="btn btn-primary" />
                </div>
            
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Bills">Πίσω στους Λογαριασμούς</a>
    </div>

</body>