MVC_Project/Models/Program.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("programs")]
public partial class Program
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string ProgramName { get; set; } = null!;

    [Column(TypeName = "text")]
    public string Benefits { get; set; } = null!;

    [Column(TypeName = "decimal(5, 2)")]
    public decimal Charge { get; set; }

    [InverseProperty("ProgramNameNavigation")]
    public virtual ICollection<Phone> Phones { get; set; } = new List<Phone>();
}

MVC_Project/Models/Seller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Project.Models;

[Table("sellers")]
public partial class Seller
{
    [Key]
    [Column("Seller_id")]
    public int SellerId { get; set; }

    [Column("User_id")]
    public int UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Sellers")]
    public virtual User User { get; set; } = null!;
}

MVC_Project/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using X.PagedList.Extensions;
using MVC_Project.Filters;

namespace MVC_Project.Controllers
{
    [SessionChecker]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly LabDBContext _context;

        public AdminController(ILogger<AdminController> logger, LabDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            return View();
        }

        public IActionResult Sellers(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Sellers.Include(s => s.User);
            return View(labDBContext.ToPagedList( page ?? 1, PageSize));
        }

        public IActionResult CreateSeller()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSeller(User user)
        {
            
            try
            {
                user.Property = "Seller";

                _context.Add(user);
                await _context.SaveChangesAsync();

                var seller = new Seller
                {
                    UserId = user.UserId
                };

                _context.Add(seller);
                await _context.SaveChangesAsync();

                return RedirectToAction("Sellers");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateSeller");
            }
        }

        public async Task<IActionResult> DeleteSeller(int? id)
        {
            
            var seller = await _context.Sellers
                .Include(s => s.User)
                .FirstOrDefaultAsync(p => p.SellerId == id);

 
            _context.Users.Remove(seller.User);

            await _context.SaveChangesAsync();

            return RedirectToAction("Sellers");
        }

        public IActionResult Programs( int? page)
        {
            if (page!= null && page < 1){
                page = 1;
            }

            int PageSize = 10;

            return View(_context.Programs.ToPagedList( page ?? 1, PageSize));
        }

        public IActionResult CreateProgram()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProgram(Models.Program program)
        {
            try
            {
                _context.Add(program);
                await _context.SaveChangesAsync();
                return RedirectToAction("Programs");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateProgram");
            }
        }

        public async Task<IActionResult> EditProgram(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Programs.FindAsync(id);

            if (program == null)
            {
                return NotFound();
            }
            return View(program);
        }

        [HttpPost]
        public async Task<IActionResult> EditProgram(Models.Program program)
        {
            try
            {
                _context.Update(program);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProgramExists(program.ProgramName))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Programs");
        }

        [SkipSessionChecker]
        public IActionResult Signout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        private bool ProgramExists(string id)
        {
            return _context.Programs.Any(e => e.ProgramName == id);
        }
    }
}

MVC_Project/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using MVC_Project.ViewModels;
using X.PagedList.Extensions;
using MVC_Project.Filters;

namespace MVC_Project.Controllers
{
    [SessionChecker]
    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;
        private readonly LabDBContext _context;

        public ClientController(ILogger<ClientController> logger, LabDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {

            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            return View();
        }

        public async Task<IActionResult> Bills(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(c => c.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(d => d.PhoneNumber).ToList();

            var bills = _context.Bills
                .Include(e => e.PhoneNumberNavigation)
                .Where(e => phoneNumbers.Contains(e.PhoneNumber));

            return View(bills.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.PhoneNumberNavigation)
                .FirstOrDefaultAsync(c => c.BillId == id);

            if (bill == null)
            {
                return NotFound();
            }

            var calls = await _context.Calls
                .Where(d => d.BillId == id)
                .ToListAsync();

            var viewModel = new BillDetailsViewModel
            {
                Bill = bill,
                Calls = calls
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Calls(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(b => b.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(c => c.PhoneNumber).ToList();

            var calls = _context.Calls
                .Include(d => d.PhoneNumberNavigation)
                .Where(d => phoneNumbers.Contains(d.PhoneNumber));

            return View(calls.ToPagedList(page ?? 1, PageSize));
           
        }

        public async Task<IActionResult> Bills_Payment(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var userId = Int32.Parse(HttpContext.Session.GetString("UserId"));

            var clients = await _context.Clients
                .Where(b => b.UserId == userId)
                .ToListAsync();

            var phoneNumbers = clients.Select(c => c.PhoneNumber).ToList();

            var bills = _context.Bills
                .Include(d => d.PhoneNumberNavigation)
                .Where(d => phoneNumbers.Contains(d.PhoneNumber) && d.Payed == false);

            return View(bills.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> Pay_Form(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.PhoneNumberNavigation)
                .FirstOrDefaultAsync(m => m.BillId == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        [HttpPost]
        public async Task<IActionResult> Pay_Procedure(int card_number, string name, int expiration, int cvv_code, int bill)
        {
            var bill_updated = await _context.Bills.FindAsync(bill);

            if (bill_updated == null)
            {
                return NotFound();
            }

            bill_updated.Payed = true;

            _context.Update(bill_updated);

            await _context.SaveChangesAsync();

            return RedirectToAction("Bills_Payment");
        }

        [SkipSessionChecker]
        public IActionResult Signout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

MVC_Project/Controllers/SellerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using MVC_Project.ViewModels;
using X.PagedList.Extensions;
using MVC_Project.Filters;

namespace MVC_Project.Controllers
{

    [SessionChecker]
    public class SellerController : Controller
    {
        private readonly ILogger<SellerController> _logger;
        private readonly LabDBContext _context;

        public SellerController(ILogger<SellerController> logger, LabDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            return View();
        }

        public IActionResult Clients(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Clients.Include(c => c.PhoneNumberNavigation).Include(c => c.User);

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public IActionResult CreateClient()
        {
            ViewBag.ProgramNames = new SelectList(_context.Programs, "ProgramName", "ProgramName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateClient(CreateClientViewModel createClientViewModel)
        {

            try { 
                _context.Add(createClientViewModel.User);
                await _context.SaveChangesAsync();


                _context.Add(createClientViewModel.Phone);
                await _context.SaveChangesAsync();

                createClientViewModel.Client.UserId = createClientViewModel.User.UserId;
                createClientViewModel.Client.PhoneNumber = createClientViewModel.Phone.PhoneNumber;
           

                _context.Add(createClientViewModel.Client);
                await _context.SaveChangesAsync();

                return RedirectToAction("Clients");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateClient");
            }
        }

        public IActionResult Phones(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Clients.Include(c => c.PhoneNumberNavigation).Include(c => c.User);

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public async Task<IActionResult> EditPhone(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Phones.FindAsync(id);

            if (program == null)
            {
                return NotFound();
            }

            ViewBag.ProgramNames = new SelectList(_context.Programs, "ProgramName", "ProgramName");
            return View(program);
        }

        [HttpPost]
        public async Task<IActionResult> EditPhone(Phone phone)
        {
            try
            {
                _context.Update(phone);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhoneExists(phone.PhoneNumber))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction("Phones");
        }

        public IActionResult Bills(int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var labDBContext = _context.Bills;

            return View(labDBContext.ToPagedList(page ?? 1, PageSize));
        }

        public IActionResult CreateBill()
        {
            ViewData["PhoneNumber"] = new SelectList(_context.Phones, "PhoneNumber", "PhoneNumber");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBill(Bill bill)
        {
            try
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction("Bills");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("CreateBill");
            }
        }

        public IActionResult ClientCalls(string phonenumber, int? page)
        {
            if (page != null && page < 1)
            {
                page = 1;
            }

            int PageSize = 10;

            var calls = _context.Calls
                .Where(b => b.PhoneNumber == phonenumber) ;

            ViewBag.PhoneNumber = phonenumber;

            return View(calls.ToPagedList(page ?? 1, PageSize));

        }

        [SkipSessionChecker]
        public IActionResult Signout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        private bool PhoneExists(string id)
        {
            return _context.Phones.Any(e => e.PhoneNumber == id);
        }
    }
}

MVC_Project/Views/Admin/CreateProgram.cshtml
@model MVC_Project.Models.Program

@{
    ViewData["Title"] = "Create Program";
}


<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Sellers">Δημιουργία νέου πωλητή</a></li>
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Programs">Διαχείριση προγραμμάτων</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <h2 style="margin-top: 12%">Δημιουργία Προγράμματος</h2>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateProgram">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Όνομα Προγράμματος</label>
                    <input asp-for="ProgramName" type="text" class="form-control">
                    <span asp-validation-for="ProgramName" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Παροχές</label>
                    <input asp-for="Benefits" type="text" class="form-control">
                    <span asp-validation-for="Benefits" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Κόστος</label>
                    <input asp-for="Charge" class="form-control" type="number" step="0.01">
                    <span asp-validation-for="Charge" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <button type="submit" class="btn btn-primary">Δημιουργία</button>
                </div>

            </form>
        </div>
    </div>

    <div>
        <a asp-action="Programs">Πίσω στα προγράμματα</a>
    </div>

</body>

MVC_Project/Views/Admin/CreateSeller.cshtml
@model MVC_Project.Models.User

@{
    ViewData["Title"] = "Create Seller";
}



<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Sellers">Δημιουργία νέου πωλητή</a></li>
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Programs">Διαχείριση προγραμμάτων</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>
            


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <h2 style="margin-top: 12%">Δημιουργία χρήστη</h2>


    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateSeller">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Username</label>
                    <input asp-for="Username" type="text" class="form-control">
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Password</label>
                    <input asp-for="Password" type="text" class="form-control">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Όνομα</label>
                    <input asp-for="FirstName" type="text" class="form-control">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="mb-3" style="padding: 2px;">
                    <label class="form-label">Επώνυμο</label>
                    <input asp-for="LastName" type="text" class="form-control">
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Δημιουργία" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Sellers">Πίσω στους πωλητές</a>
    </div>
</body>

MVC_Project/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Index";
}

<body style="background-image: url('https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'); background-attachment: fixed; background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light box-shadow mb-3 fixed-top position-fixed" style="margin:1% 15% 0% 15%; border-radius: 14px; background: rgba(255,255,255,0.8); backdrop-filter: blur(10px); border-color: lightgray; border-width: 1.8px; border-style: solid">
        <div class="container-fluid">
            <a class="navbar-brand disabled" style="cursor: default;">MVC Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-xl-grow-1 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index">Αρχική</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πελάτες
                        </a>
                        <ul class="dropdown-menu text-dark">
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills">Προβολή λογαριασμού</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Calls">Προβολή ιστορικού κλήσεων</a></li>
                            <li><a class="dropdown-item" asp-controller="Client" asp-action="Bills_Payment">Εξόφληση λογαριασμού</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" tabindex="-1" aria-disabled="true">
                            Διαχειριστές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Sellers">Διαχείριση πωλητών</a></li>
                            <li><a class="dropdown-item" asp-controller="Admin" asp-action="Programs">Διαχείριση προγραμμάτων</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark disabled" style="color: gray; opacity: 0.5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Πωλητές
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Καταχώρηση νέου πελάτη</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Έκδοση Λογαριασμού πελατών</a></li>
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Login">Διαχείριση πελάτη</a></li>
                        </ul>
                    </li>
                </ul>
            


            <a class="nav-link text-dark" style="background-color:burlywood; border-radius: 6px; font-weight: bold" asp-action="Signout">Αποσύνδεση</a>

            </div>
        </div>
    </nav>

    <div style="margin: 25% 25% 2% 25%">
        <h1 style="text-align:center;"> Καλωσήρθες @ViewBag.FirstName</h1>
        <div style="margin: 5% 0% 0% 0%">
            <h5 style="text-align: center;"> Έχετε συνδεθεί ως Διαχειριστής </h5>
            <h5 style="text-align:center"> Επέλεξε από την επιλογή "Διαχειριστές" την ενέργεια που επιθυμείς!</h5>
        </div>

    </div>

</body>